### ISSUE TITLE
Spotify and LinkedIn links don't work

### ISSUE THREAD

**Issue by jessemillar** [becheran/mlc#12]
**Describe the bug**
See title.

**To Reproduce**
Try to validate either https://www.linkedin.com/in/jessemillar or https://open.spotify.com/playlist/1zl6faUb2RkH9eE6LwA0ae via `mlc`.

**Expected behavior**
I'd expect the links to validate since they work in a browser.

**Screenshots**
```
[Err ] ./linkedin/index.html (12, 51) => https://www.linkedin.com/in/jessemillar. Http(s) request failed. error sending request for url (https://www.linkedin.com/in/jessemillar): invalid HTTP status-code parsed
[Err ] ./spotify/4-3-2020/index.html (12, 51) => https://open.spotify.com/playlist/1zl6faUb2RkH9eE6LwA0ae. 400 - Bad Request
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
 - Rust: rustc 1.43.1 (8d69840ab 2020-05-04)

**Comment by becheran** [comment]
Thanks for raising these issues. 

I just checked both links and it seems like it will not be possible to automatically check them via mlc. Linkedin seems to not like robots. They return a 400 and when I do open it in my browser I get a capchar were I have to manually confirm that I am not a robot by typing a text.

With spotify it is also tricky. They send the response code 999 for head and get requests. This seems OK for the browser, which might just ignore this (undefined) http status code, but not for the rust lib I use. They simply give me an status code parsing error.

I am sorry, but I guess you have to ignore those links

**Comment by jessemillar** [comment]
Thank you very much for digging in and sharing your findings. That all makes perfect sense. I've ignored the errors in my CI/CD usage of `mlc`.
