### ISSUE TITLE
Option to throttle connections to each domain

### ISSUE THREAD

**Issue by tocklime** [becheran/mlc#13]
**Is your feature request related to a problem? Please describe.**
If you have more than a couple github.com links in your markdown files, then you get lots of `429 - Too Many Requests` responses when you run mlc.

**Describe the solution you'd like**
Limit the web requests so that there is at least N (milli)seconds between each request to each domain.

**Describe alternatives you've considered**
A global throttle would be simpler to implement, but at a much higher run time cost.

**Comment by tocklime** [comment]
I guess another alternative would be to detect the 429 response and behave accordingly (probably by auto-applying this throttle behaviour), but it's probably best to be polite in the first place, rather than wait until you've been told off.

**Comment by becheran** [comment]
Thank you very much for your feature request. I never experienced this, but I can imagine that one gets this frequently if sending requests to the same domain over and over again. 

You are right. The best option would be to first group the domains and then do throttling for each domain individually. Right now I won't have the time to implement this. Maybe next weekend I can take a look.

**Comment by becheran** [comment]
With release 0.13.0 a throttle option was added. The checking mechanism was also changed so that URLs that exist multiple times will only be checked once. Maybe this already solves you issue, otherwise try the --throttle option which will slow down execution speed.
