### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by benmoss** [becheran/mlc#17]
**Describe the bug**
I tried to use the docker image to avoid having to install Rust on OSX, where there's no precompiled binaries.

I got this error from all the HTTP requests:
> [Err ] /capi/docs/book/src/developer/providers/implementers-guide/controllers_and_reconciliation.md (201, 13) => https://godoc.org/sigs.k8s.io/cluster-api/util#GetOwnerMachine. Http(s) request failed. error sending request for url (https://godoc.org/sigs.k8s.io/cluster-api/util#GetOwnerMachine): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get local issuer certificate)

I'd guess that something isn't configured correctly with system certificates in the docker image.

**To Reproduce**
```
docker run --rm becheran/mlc bash -c "echo [hi]\(https://google.com\) > foo.md && mlc foo.md"

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                                                          +
+            markup link checker - mlc v0.13.1             +
+                                                          +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Head request error: error sending request for url (https://google.com/): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify
failed:ssl/statem/statem_clnt.c:1915: (unable to get local issuer certificate). Retry with get-request.
[Err ] foo.md (1, 6) => https://google.com. Http(s) request failed. error sending request for url (https://google.com/): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (unable to get local issuer certificate)

The following links could not be resolved:
foo.md (1, 6) => https://google.com.

Result (1 links):

OK       0
Skipped  0
Warnings 0
Errors   1
```

**Comment by becheran** [comment]
I could reproduce the issue on my system. Seems to be that https requests are not working correctly in docker. The link `http://google.com/` works just fine in docker.

**Comment by becheran** [comment]
The issue should be fixed with release _0.13.4_. Thanks for reporting and give it a try once the docker image is available on Docker Hub and works for you so I can close the issue.

**Comment by benmoss** [comment]
Thanks for the quick fix, it looks good now!
