### ISSUE TITLE
Support checking anchor links

### ISSUE THREAD

**Issue by mvlabat** [becheran/mlc#19]
It would be great if this tool was able to check anchor links. It would really help to maintain references to internal MD docs. (But if it could also parse external html resources, that would be beyond awesomeness 😃 ).

I guess it can be introduced with a CLI option to enable or disable anchor link checks.

And thanks for creating this tool! Looking forward to replacing `markdown-link-check` with it :)

**Comment by becheran** [comment]
Definitely a nice feature. I am pretty sure that it won't be super simple to implement though. For external resources I don't even know how this should be possible.

Right now I won't have the time to add this feature unfortunately.

**Comment by dvtomas** [comment]
Yeah, this would be very nice. I use those with [GitLab docs](https://docs.gitlab.com/ee/user/markdown.html#header-ids-and-links)  extensively. Sometimes, I even use custom anchors:

```
### This is a very long header {#long-header}

Let's [link to it](#long-header)
```

It doesn't work for all markdown implementations, but it is easily recognizable, so adding support for it probably shouldn't be that complicated.

**Comment by becheran** [comment]
Ticket #31 tracks progress for anchor link implementation
