### ISSUE TITLE
crates.io links cannot be resolved

### ISSUE THREAD

**Issue by stanislav-tkach** [becheran/mlc#20]
No crates.io links can be resolved. For example, a file only contains a single link:
```md
https://crates.io/crates/tokio
```
`mlc` gives the following output:
```
> mlc

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                                                          +
+            markup link checker - mlc v0.13.4             +
+                                                          +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[Err ] ./test.md (1, 1) => https://crates.io/crates/tokio. 404 - Not Found

Result (1 links):

OK       0
Skipped  0
Warnings 0
Errors   1


The following links could not be resolved:

./test.md (1, 1) => https://crates.io/crates/tokio.
```

By the way, are all browser and smartphone details in the issue template really needed for this project?

**Comment by becheran** [comment]
Hey, thank you very much for opening an issue. Unfortunately I cannot really solve this issue. All crates.io pages have the same problem. I also get a 404 when I query the page with curl `curl https://crates.io/crates/tokio {"errors":[{"detail":"Not Found"}]}` I guess it is intentionally that crates.io shall only be visible to web-browsers.

And yes, I will update the template. Absolutely no need for this info.

**Comment by mvlabat** [comment]
@becheran I believe this can be worked around with adding this header to the requests: `Accept: text/html`
https://github.com/rust-lang/crates.io/issues/788

**Comment by becheran** [comment]
Right. Thanks @mvlabat. I added the header info and it works. I will push and release an updated version with the fix. Many thanks

**Comment by stanislav-tkach** [comment]
Thanks for the quick response!
