### ISSUE TITLE
Unable to extract link if on the same line as inline code block

### ISSUE THREAD

**Issue by alexiri** [becheran/mlc#34]
**Describe the bug**
mlc currently fails to find a valid link if it's on the same line as an inline code block.

**To Reproduce**
1. This md file:
```
`bug` [code](http://example.net/), link!.
```
2. This command: 'mlc .'
3. See error: no link found

**Expected behavior**
A link should be found

**Additional context**
Test case submitted in PR #33.

**Comment by becheran** [comment]
Thanks for reporting! 
Fixed in PR #33. Release `0.14.3` contains the fix.
