### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by hoijui** [becheran/mlc#37]
When supplying a switch, e.g. `--offline`, `mlc` would not try to access anything outside the local machine.
Might this also need a new, neutral result state?

This can be useful when working off-grid, and still wanting at least a preliminary (very fast) check of the docu, before committing.

It might only check local links, or use a cache of earlier checked links.

Priority: low

**Comment by becheran** [comment]
I already added a [`--no-web-links`](https://github.com/becheran/mlc/blob/master/docs/reference.md) option to `mlc`. Is this what you want? Actually I do prefer the much simpler arg `--offline`. Maybe I change it and keep the other as deprecated?

**Comment by hoijui** [comment]
doh! :D
yes of course, that is what I meant, thanks. :-)

**Comment by becheran** [comment]
Because I don't want to introduce a breaking change, I will keep `--no-web-link` for now
