### ISSUE TITLE
Missing binaries for 0.15.x releases

### ISSUE THREAD

**Issue by diegorondini** [becheran/mlc#49]
**Describe the bug**
Binaries for 0.15.x releases are missing in the release page:
https://github.com/becheran/mlc/releases

**To Reproduce**
Run the command in the README:
```
$ curl -L https://github.com/becheran/mlc/releases/download/v0.15.2/mlc -o mlc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     32      0 --:--:-- --:--:-- --:--:--    32
$ file mlc 
mlc: ASCII text, with no line terminators
$ cat mlc
Not Found
```

**Comment by becheran** [comment]
I know :(. Thanks for reporting, I quickly uploaded the artifacts for 15.2 manually. The gitlab pipeline release jobs are somehow broken. Need to fix them. I keep this issue open till done. Meanwhile I hope you can work with the binaries I just manually uploaded.

**Comment by diegorondini** [comment]
I was using `cargo install` in the meantime, but of course it's not convenient for a pipeline.

Thanks for uploading the binaries.
Remember to update the curl in the README, it should be:
```
curl -L https://github.com/becheran/mlc/releases/download/v0.15.2/mlc-x86_64-linux -o mlc
```
