### ISSUE TITLE
Support for ignore link list from a file

### ISSUE THREAD

**Issue by diegorondini** [becheran/mlc#51]
**Is your feature request related to a problem? Please describe.**
At the moment the links to ignore are provided as option parameters on the command line:
```
mlc -i '<mylinktoignore>'
```
This is inconvenient if mlc is run during a pipeline, as adding / removing a link to ignore requires changing the pipeline config file.

**Describe the solution you'd like**
Allow to specify a file that provides the list of links to ignore. This would allow to just edit the file to change the list of links to ignore, like when you edit `.gitignore` to specify the files / dirs that should be ignored by `git`.

**Comment by becheran** [comment]
Sounds reasonable. I will think about it. Maybe even more general such as a *mlc* config file which does include the ignored link list.

**Comment by diegorondini** [comment]
Yes, that sounds like a sensible idea, and matches what others similar projects are doing:
https://github.com/tcort/markdown-link-check#config-file-format

**Comment by diegorondini** [comment]
Thanks for implementing this!
