### ISSUE TITLE
Latest Docker images broken

### ISSUE THREAD

**Issue by fresh2dev** [becheran/mlc#53]
**Describe the bug**

v0.15.x Docker images are broken.

**To Reproduce**

1. Run and observe v0.15.2 does not work:

```
➜ docker run --rm -it becheran/mlc:0.15.2 mlc -h

mlc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by mlc)
```

**Expected behavior**

`mlc` should continue to function in Docker like v0.14.3 does.

```
➜ docker run --rm -it becheran/mlc:0.14.3 mlc -h

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                                                          +
+            markup link checker - mlc v0.14.3             +
+                                                          +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Desktop (please complete the following information):**

```
➜ docker --version

Docker version 20.10.14, build a224086
```

**Comment by becheran** [comment]
@fresh2dev thank you very much for reporting and sorry for the slow response. The image is fixed with 0.15.3. The problem was that the rust binary requires GLIBC_2.28 which was not part of ubuntu 18.04. Updating the baseimage to 20.04 fixed the issue.
