### ISSUE TITLE
Evaluate keeping compatibility with some not-so-old glibc

### ISSUE THREAD

**Issue by diegorondini** [becheran/mlc#69]
If you try to run the precompiled `mlc-x86_64-linux` binary on latest stable Debian 11 bullseye you'll get:
```
# ./mlc
./mlc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./mlc)
./mlc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./mlc)
./mlc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./mlc)
```
This is due to Debian 11 using glibc 2.31:
```
# ldd --version
ldd (Debian GLIBC 2.31-13+deb11u5) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

The glibc version on Debian is not so old, so it would be nice to build the `mlc` binary with compatibility for Debian stable.

A similar issue is discussed here:
https://github.com/atanunq/viu/issues/68

Thank you

**Comment by diegorondini** [comment]
This may help as well:
https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html

**Comment by hoijui** [comment]
In all my rust projects I use a set of build scripts where I build with [MUSL](https://musl.libc.org/),
to make the result work on most 64bit platforms,
bypassing such problems:
https://github.com/hoijui/rust-project-scripts

deps can be installed like this:

```
sudo apt-get install -y --no-install-recommends \
	build-essential \
	musl-tools
```

or in a GitHub action:

```
      - name: "Get the Rust toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
            targets: x86_64-unknown-linux-musl
            components: rustfmt, clippy
```

When MUSL is setup on the build machine, it is as simple as this:

```
cargo build --release --target=x86_64-unknown-linux-musl
```

**Comment by hoijui** [comment]
In my scripts I then also strip off the debug symbols to make the binary smaller, e.g.:

```
strip mlc
```

I like the MUSL approach, because .. if one really wants a binary adjusted to ones local system, one can compile it specifically for that, while a MUSL build works well for distributing to many without much hassle.

**Comment by becheran** [comment]
@hoijui I gave it a try, but it seems to have some issues building the openssl lib using musl: https://github.com/becheran/mlc/actions/runs/4535771495/jobs/7991624624

**Comment by becheran** [comment]
@hoijui I managed to build for musl after adding musl gcc to my pipeline.

@diegorondini could you please give the following binary a try if it works on your system? https://github.com/becheran/mlc/suites/11842546138/artifacts/618804496

If so, I will pull my branch into main and build using musl instead of glibc.

**Comment by diegorondini** [comment]
@becheran that binary does indeed work on Debian 11 (Official python 3.11 docker container - https://hub.docker.com/_/python).

Thanks for your effort!

**Comment by hoijui** [comment]
yep works here too! :-)
I am also on debian testing (I think that is currently 11) with my local system.
