### ISSUE TITLE
Option to (maybe conditionally) hide redirects

### ISSUE THREAD

**Issue by EagleoutIce** [becheran/mlc#84]
**Is your feature request related to a problem? Please describe.**
In our project we have a lot of redirects in our links (most as simple as GitHub redirecting the link to the specific blob). With this, each Pull-Request is cluttered with warnings about the redirect.

**Describe the solution you'd like**
Probably, a flag along the line of `--do-not-warn-for-redirect` would suffice. 
Something like `--do-not-warn-for-redirect-to "https://github.com/*"` similar to the `--ignore-links` option would be nice too!

**Describe alternatives you've considered**
We could use `--ignore-links` but with this we loose all information on if the target is reachable or not.

**Additional context**
If desired i can try to implement the feature.

**Comment by becheran** [comment]
Sounds good. I think your proposal with the additional argument sounds like a good idea. If you want and have the time you can create a pr for this. It should not be too hard to implement.

Otherwise I don't know when I will find the time to do it right now to be honest.

**Comment by EagleoutIce** [comment]
With this being part of v0.17.0 (thank you for the release!) - can the issue be closed? Or do you have further plans? :)
